# Generated by Django 3.0.7 on 2026-04-12 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0015_auto_20200727_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='venue',
            field=models.CharField(
                help_text='Optional workshop venue or city',
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
